version: '3.8'

services:
  coindesk:
    image: minhthongnguyen/coindesk:homework
    container_name: coindesk
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ENV.DATASOURCE.USERNAME: sa
      ENV.DATASOURCE.PASSWORD: 123456
      ENV.DATASOURCE.CRON-TRIGGER: 0 */5 * * * ?
    depends_on:
      - db
  db:
    image: "buildo/h2database"
    ports:
      - "1521:1521"