spring:
  application:
    name: coindesk
  datasource:
    url: jdbc:h2:mem:mydb
    username: '${env.datasource.username:sa}'
    password: '${env.datasource.password:123456}'
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: utf-8
springdoc:
  show-actuator: false
  api-docs:
    enabled: false
    path: /api-docs
  cache:
    disabled: true
  packagesToScan: com.homework.coindesk.controller
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html



server:
  coin-desk-url: '${env.server.coin-desk-url:https://api.coindesk.com/v1/bpi/currentprice.json}'

scheduler:
  cron-trigger: '${env.scheduler.cron-trigger: 0 */5 * * * ?}'