INSERT INTO CURRENCY(CODE, SYMBOL, RATE, DESCRIPTION, RATE_FLOAT, CREATED_DATE, UPDATED_DATE)
VALUES
    ('USD', '&#36;', '66,929.965', 'United States Dollar', 66929.97, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('GBP', '&pound;', '52,459.037', 'British Pound Sterling', 52459.04, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EUR', '&euro;', '62,308.25', 'Euro', 62308.25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYSTEM_CONFIG(NAME, LANGUAGE_CODE, CURRENCY_CODE)
VALUES
    ('USD', 'US', 'USD'),
    ('đô la mỹ', 'VN', 'USD');