CREATE TABLE IF NOT EXISTS CURRENCY
(
    CODE         VARCHAR(255) PRIMARY KEY,
    SYMBOL       VARCHAR(255),
    RATE         VARCHAR(32),
    DESCRIPTION  VARCHAR(255),
    RATE_FLOAT   FLOAT,
    ACTIVE       BOOLEAN   NOT NULL DEFAULT TRUE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    UPDATED_DATE TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE IF NOT EXISTS system_config
(
    id            BIGSERIAL PRIMARY KEY,
    name          VARCHAR(255),
    language_code VARCHAR(255),
    active        BOOLEAN   NOT NULL DEFAULT TRUE,
    created_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    currency_code VARCHAR(255),
    CONSTRAINT fk_currency_code FOREIGN KEY (currency_code) REFERENCES currency (code)
);
