CREATE TABLE IF NOT EXISTS CURRENCY
(
    CODE         VARCHAR(255) PRIMARY KEY,
    SYMBOL       VARCHAR(255),
    RATE         VARCHAR(32),
    DESCRIPTION  VARCHAR(255),
    RATE_FLOAT   FLOAT,
    ACTIVE       BOOLEAN   NOT NULL DEFAULT TRUE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    UPDATED_DATE TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE IF NOT EXISTS SYSTEM_CONFIG
(
    ID                BIGSERIAL PRIMARY KEY,
    NAME              VARCHAR(255),
    BY_PASS_SCHEDULER BOOLEAN   NOT NULL DEFAULT TRUE,
    ACTIVE            BOOLEAN   NOT NULL DEFAULT TRUE,
    CREATED_DATE      TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    UPDATED_DATE      TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
